### ISSUE TITLE
Can move to typings, but one item remains

### ISSUE THREAD

**Issue by unional** [unional/generator-typings#3]
@blakeembrey, `typed-typings/npm-*` naming is my last hesitation, as I still don't see the typings ties to any particular distributing channel.

If the source is distributed in npm, bower, jspm, NuGet, apm (atom), etc, or any combination of them, how should the repo be named?

I like the original `typed-*` better.

**Comment by blakeembrey** [comment]
I prefer `typed-*` better too, but it was redundant when it's the organisation name. I actually noted it in the registry because I saw people following the pattern I did accidentally. I only use `<registry>-<name>` as a way to avoid possible collisions in the future and not give preferentially treatment in the organisation. In general, that's unlikely to happen (hasn't yet).

**Comment by unional** [comment]
The generator currently would suggest user to name the repo as `typed-xyz`. Are you ok with it?

**Comment by blakeembrey** [comment]
Perfect :+1:
